/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: HyVGiMEiD1OqVjanZbsZ81mdFcU0XZwNr1PHN1KtIq1RkJS/20PovWQgmp/UU8qhEEB3OP51ouSmE7hCfZMqsQ==
 */

/* eslint-disable */
// tslint:disable

import Todos, {Todos_InsertParameters} from './todos'

interface DatabaseSchema {
  todos: {record: Todos, insert: Todos_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
