/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: fK8Wj+QwB0NmKRZOyZ4JpVBQ2htAwqKjUYvdekQNO6byg1AJVDD1diYjvRq3sU6wwemU4+qgUO6fGWoWS1GBLA==
 */

/* eslint-disable */
// tslint:disable

interface Todos {
  done: boolean
  /**
   * @default nextval('todos_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'todos_id'}
  text: string
}
export default Todos;

interface Todos_InsertParameters {
  done: boolean
  /**
   * @default nextval('todos_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'todos_id'}
  text: string
}
export type {Todos_InsertParameters}
